name: "Publish Artifacts"
description: "Publish Prod Artifacts"
inputs:
  cloudrepo_user:
    required: true
  cloudrepo_password:
    required: true
  twine_password:
    required: true
  twine_username:
    required: true
  npm_token:
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: "zulu"
        java-version: "21"

    - name: Load .env file
      uses: xom9ikk/dotenv@v2.3.0
      with:
        path: ./
        load-mode: strict

    # java
    - name: Gradle Build
      shell: bash
      run: ./gradlew build --scan

    - name: Publish Jar
      env:
        CLOUDREPO_USER: ${{ inputs.cloudrepo_user }}
        CLOUDREPO_PASSWORD: ${{ inputs.cloudrepo_password }}
        # will use the version in .env
      shell: bash
      run: ./gradlew publish

    # python - pydantic v1
    - name: Generate Python Protocol Classes
      shell: bash
      run: protocol-models/bin/generate-python-pydantic.sh

    # python - pydantic v2
    - name: Generate Python Protocol Classes
      shell: bash
      run: protocol-models/bin/generate-python-pydantic-v2.sh

    # python - dataclasses
    - name: Generate Python DataClasses Protocol Classes
      shell: bash
      run: protocol-models/bin/generate-python-dataclasses.sh

    - name: Publish Python Package
      uses: mariamrf/py-package-publish-action@v1.1.0
      with:
        # specify the same version as in ~/.python-version
        python_version: "3.9.11"
        pip_version: "21.1"
        subdir: "protocol-models/python/airbyte_protocol"
      env:
        TWINE_PASSWORD: ${{ inputs.twine_password }}
        TWINE_USERNAME: ${{ inputs.twine_username }}

    - name: Publish Pydantic-v2 Python Package
      uses: mariamrf/py-package-publish-action@v1.1.0
      with:
        # specify the same version as in ~/.python-version
        python_version: "3.9.11"
        pip_version: "21.1"
        subdir: "protocol-models/python/airbyte_protocol_pdv2"
      env:
        TWINE_PASSWORD: ${{ inputs.twine_password }}
        TWINE_USERNAME: ${{ inputs.twine_username }}

    - name: Publish DataClasses Python Package
      uses: mariamrf/py-package-publish-action@v1.1.0
      with:
        # specify the same version as in ~/.python-version
        python_version: "3.9.11"
        pip_version: "21.1"
        subdir: "protocol-models/python/airbyte_protocol_dataclasses"
      env:
        TWINE_PASSWORD: ${{ inputs.twine_password }}
        TWINE_USERNAME: ${{ inputs.twine_username }}

    # github runners already come with NPM and node
    - name: Generate Typescript Protocol Classes
      shell: bash
      run: protocol-models/bin/generate-typescript-classes-docker.sh

    - name: npm publish
      shell: bash
      working-directory: protocol-models/typescript
      run: |
        npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
        npm publish
      env:
        NPM_TOKEN: ${{ inputs.npm_token }}
