name: Publish to PyPi Manually
on:
  workflow_dispatch:
    inputs:
      repo:
        description: "Repo to check out code from. Defaults to the airbyte protocol repo."
        required: false
        default: "airbytehq/airbyte-protocol"
      gitref:
        description: "The git ref to check out from the specified repository."
        required: false
        default: master
      publish-test-pypi:
        description: 'Publish to Test PyPi'
        type: boolean
        required: true
        default: true
      publish-pypi:
        description: 'Publish to PyPi'
        type: boolean
        required: true
        default: true

concurrency:
  group: publish-to-pypi
  cancel-in-progress: false

jobs:
  publish-protocol:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Airbyte
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.gitref }}

      - name: Generate Protocol Classes
        run: protocol-models/bin/generate-python-classes-docker.sh

      - name: Publish Python Package to test.pypi.org
        if: github.event.inputs.publish-test-pypi
        uses: mariamrf/py-package-publish-action@v1.1.0
        with:
          # specify the same version as in ~/.python-version
          python_version: "3.9.11"
          pip_version: "21.1"
          subdir: "protocol-models/python/"
        env:
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_REPOSITORY_URL: "https://test.pypi.org/legacy/"
      - name: Publish Python Package
        if: github.event.inputs.publish-pypi
        uses: mariamrf/py-package-publish-action@v1.1.0
        with:
          # specify the same version as in ~/.python-version
          python_version: "3.9.11"
          pip_version: "21.1"
          subdir: "protocol-models/python/"
        env:
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
